version: '3.7'

services:
  php-7-64m:
    build:
      context: .
      dockerfile: docker/php-7/Dockerfile
    volumes:
      - ./PHP:/var/www/app/php
    mem_limit: 64M
    mem_reservation: 64M
    cpus: 0.5

  php-7-128m:
    build:
      context: .
      dockerfile: docker/php-7/Dockerfile
    volumes:
      - ./PHP:/var/www/app/php
    mem_limit: 128M
    mem_reservation: 128M
    cpus: 0.5

  php-7-256m:
    build:
      context: .
      dockerfile: docker/php-7/Dockerfile
    volumes:
      - ./PHP:/var/www/app/php
    mem_limit: 256M
    mem_reservation: 256M
    cpus: 0.5